### PR TITLE
Adding Java-17 to NESSI 2022.10

### PR DESCRIPTION
**Pull request by poksumdo**
Also removed the section testing if the fix for https://github.com/EESSI/software-layer/issues/191 works (it did/does).

### CODE REVIEW

**Comment by poksumdo** [comment]
Patch seems to work. Adding label bot:build.

**Comment by poksumdo** [comment]
It seems all needed builds are done. Adding label bot:deploy.

**Comment by poksumdo** [comment]
Built and ingested for every target. Ready to merge.

**Review by trz42 — APPROVED** [review]
Works. Nice.

**Pull request merged**
