### PR TITLE
More basic packages (Qt5, SciPy-bundle) for NESSI pilot 2021.12

### PR DESCRIPTION
**Pull request by trz42**
Adding:

- Qt5-5.14.1-GCCcore-9.3.0
- SciPy-bundle-2020.03-foss-2020a-Python-3.8.2

### CODE REVIEW

**Comment by trz42** [comment]
Build of Qt5 was successful on ex3, but the build script crashed because of a typo. On AWS (CitC) and Fox the build failed. Increased memory for job on Fox. Investigating on AWS. Resending event.

**Comment by trz42** [comment]
Trying to secure node local tmp on AWS (CitC). Stopped bot on Fox and ex3. Resending event.

**Comment by trz42** [comment]
Last version of securing `/tmp` on a compute node may not have been correct. Resending event.

**Comment by trz42** [comment]
Ingested successful build for `zen`. Also ingested partial builds for `zen3` and `haswell`. The temporary directory is not copied. Will add a bit more debugging and and resend event.

**Comment by trz42** [comment]
Reconfigure bot on `ex3` to build for `zen2`. Temporarily disable bot on CitC and Fox. Resend event.

**Comment by trz42** [comment]
Build package for `haswell` on NREC.

**Comment by trz42** [comment]
No luck with Qt5 on `haswell`. Skipping it and dependent packages (of the currently available packages in the EESSI pilot 2021.12 apparently only OpenFOAM depends on Qt5). Can later revisit this, e.g., trying a different Qt5 version (for example, starting with 5.14.2 vs 5.14.1) and, if Qt5 builds then, test if OpenFOAM can be built with a newer version of Qt5.

**Review by poksumdo — APPROVED** [review]
All is built except Qt5 for `haswell` despite myriads of attempts. Skipping that for the moment. Issue #30 has been opened to not forget to revisit this PR.

**Pull request merged**
