### PR TITLE
Adding GCC 9.3 & 10.3 to NESSI 2022.10

### PR DESCRIPTION
**Pull request by poksumdo**
Trying both versions in one PR.

### CODE REVIEW

**Comment by poksumdo** [comment]
Applying patch succeeded. Adding label bot:build.

**Comment by poksumdo** [comment]
Everything was built. Nice!

**Comment by trz42** [comment]
All built successfully. All ingested. Wow.

Ready to merge.

**Review by trz42 — APPROVED** [review]
All fine and done.

**Pull request merged**
